### PR TITLE
Fixes #2 – Replaces `lemonade.css` with bootstrap v4

### LINKED ISSUE #15: Site isn't very mobile friendly
I mentioned cmder to a friend recently. Their reaction was to look it up on their phone. This was the experience they got:

image
image

😦

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
I'm working on a rewrite of the Cmder.net website, which fixes some unreadability mentioned in #15 and adds some Javascript for a better user experience.

### Responsiveness
This patch replaces the [lemonade.css](https://github.com/dope/lemonade) (a simple grid system) with more robust bootstrap. Since the **bootstrap v4.0** by default uses [_flexboxes_](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) instead of manual widths, the content will be shown on mobile _beautifully:_

  

This essentially fixes #15.

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
@MartiUK & @Jackbennett 
Can you have a look at CI, please? It's acting up

**Comment by Stanzilla** [comment]
@DRSDavidSoft try with https://github.com/DRSDavidSoft/cmderdev.github.io/pull/5

**Comment by DRSDavidSoft** [comment]
@Stanzilla Thanks, seems to have fixed the CI problem!

**EDIT:** Oh no, it still has the error:
External link https://gitforwindows.org/ failed: response code 0 means something's wrong.

**Comment by Stanzilla** [comment]
https://github.com/gjtorikian/html-proofer/pull/322

**Comment by Stanzilla** [comment]
I don't even understand why it wants to curl that...

**Comment by DRSDavidSoft** [comment]
https://github.com/cmderdev/cmderdev.github.io/blob/450274d0cda50e16ac5ab83c4916dc1f75457938/Gemfile#L4

The `html-proofer` wants to check all the links and make sure they're valid, but git for windows website already works 😕

**Comment by Stanzilla** [comment]
try https://github.com/DRSDavidSoft/cmderdev.github.io/pull/6

**Comment by DRSDavidSoft** [comment]
@Stanzilla Hm, this seems to do it. I'm also merging your commits into my `rewrite` branch, this `release-pr` branch is for creating the pull request.

Also, have a look at this if you're interested: (git clone it first)
https://github.com/DRSDavidSoft/cmder-site/blob/feat/interactive-cmder/.workspace/cmder-web.html

`git clone https://github.com/DRSDavidSoft/cmderdev.github.io.git`

**Comment by Stanzilla** [comment]
Hah, that's neat, what are your plans for it?

**Comment by DRSDavidSoft** [comment]
@Stanzilla I have explained it here: https://github.com/DRSDavidSoft/cmderdev.github.io/issues/12#issue-318780136

**Comment by DRSDavidSoft** [comment]
@MartiUK Ready to merge?

**Comment by DRSDavidSoft** [comment]
@Jackbennett Could you squash and merge this please?

**Comment by DRSDavidSoft** [comment]
## Ready to merge
Please **squash and merge** to avoid multiple commits.
<sup>(CC'd @Stanzilla @MartiUK @Jackbennett)</sup>

Awaiting your response

**Comment by Stanzilla** [comment]
Looks good! 👌 I don't have permissions on the repo so gotta wait for the other guys :)

**Comment by MartiUK** [comment]
LGTM 👍

**Pull request merged**
