### PR TITLE
point all download links to GitHub's `latest` release page

### PR DESCRIPTION
**Pull request by Stanzilla**

### CODE REVIEW

**Comment by Jackbennett** [comment]
~~I see marti has a review request.~~ I learned how to use the request review button. 

That's good because I presume those are your google tracking links? Might have to think about what this change does to the stats if you're tracking it.

**Comment by Stanzilla** [comment]
Yeah I wasn't sure how best to handle it but I think it is fine, it will still track how many people are interested in the different editions, only downside is that they have to click twice now.

**Comment by Stanzilla** [comment]
@MartiUK

**Review by MartiUK — CHANGES_REQUESTED** [review]
These are download buttons, I don't think it's right to redirect to the release page in github, when a user would be expecting a download.

**Comment by Stanzilla** [comment]
@MartiUK any suggestions then on how to better handle this? Don't list the files at all and just say "Download the latest release on our GitHub page"? I didn't do that because I didn't want you to lose the analytics data.

**Comment by MartiUK** [comment]
The analytics isn't in my control, I assume it's with @samvasko.

We can do this for now, I'm working on a solution that'll use the github api.

**Comment by Stanzilla** [comment]
Do what now? The current PR or my last suggestion?

**Review by MartiUK — APPROVED** [review]

**Comment by MartiUK** [comment]
Current PR

**Comment by Stanzilla** [comment]
Alright, I can't merge myself btw.

**Pull request merged**
