### PR TITLE
Add getlatest downloads

### PR DESCRIPTION
**Pull request by MartiUK**
Automatically fetches the latest release urls for the site, additionally if javascript is disabled it will default to the "latest" release page.

### CODE REVIEW

**Comment by Stanzilla** [comment]
very nice!

**Review by Stanzilla — APPROVED** [review]

**Comment by DRSDavidSoft** [comment]
@MartiUK great idea but you forgot to `break` the cases!
https://github.com/cmderdev/cmder/issues/1563

I fixed it, and also added a few more lines to also set the file size automatically.
Merge #19 If you approve! :)

**Comment by MartiUK** [comment]
@DRSDavidSoft Thanks, I'm not a web developer as you may have noticed 😆

**Comment by DRSDavidSoft** [comment]
@MartiUK It's cool, I appreciate your development in other fields. Cmder is gold to me!

**Pull request merged**
