### PR TITLE
Add updated links

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
### Description
Adding some missing links to the website.

@MartiUK Could you please add me as a contributor to this repo too? Would like to work on some updates for 2023!

### CODE REVIEW

**Comment by MartiUK** [comment]
Looks like your merge wiped out your changes

**Review by MartiUK — CHANGES_REQUESTED** [review]
Looks like you wiped out your changes, try a rebase?

**Comment by DRSDavidSoft** [comment]
Hey there, it seems there is a mistake on my part. I checked the master and it seems these commits were somehow merge in back when I made them, so this PR is probably referencing orphan commits.

Could you please add me as a contributor to this repo as well? I'd like to tweak some design aspects to bring it to 2023 standards. First, I was thinking of migrating Bootstrap 4 to Bootstrap 5, or maybe even Tailwind CSS.

**Comment by MartiUK** [comment]
> Could you please add me as a contributor to this repo as well? I'd like to tweak some design aspects to bring it to 2023 standards. First, I was thinking of migrating Bootstrap 4 to Bootstrap 5, or maybe even Tailwind CSS.

This has been done.

**Pull request closed without merging**
